# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-25 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_03', '0002_auto_20181224_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(),
        ),
    ]
