# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-26 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool_03', '0003_auto_20181225_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('create_at',)},
        ),
    ]
