# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-26 23:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool_03', '0004_auto_20181226_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
    ]
